#ifndef RESPONSE_CODES_H
#define RESPONSE_CODES_H

#define SUCCESS 0
#define WRONG_PARAMETERS_ERROR 1
#define CONFIGURATION_ERROR 2
#define UNABLE_TO_OPEN_FILE_ERROR 3
#define FILE_UPLOAD_ERROR 4
#define FILE_DOWNLOAD_ERROR 5

#endif
